money/urls.py
from django.urls import path
from money import views


app_name = 'money'

urlpatterns = [
    path('manage-accounts/', views.manage_account, name='mange_accounts'),
    path('list-account/', views.account_list, name='list_account'),
    path('add-account/', views.add_account, name='add_account'),
    path('edit-account/<int:pk>/', views.edit_account, name='edit_account'),

    path('add-money/', views.add_money, name='add_money'),
]

moneytracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
    path('user/', include('users.urls')),
    path('dashboard/money/', include('money.urls')),
    path('dashboard/income-expense/', include('income_expense.urls')),
    path('dashboard/transaction/', include('transaction_period.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

money/models.py
from django.db import models
from django.db.models import Sum
from model_utils import Choices

from transaction_period.models import TransactionPeriod
from users.models import User

ACCOUNT_TYPE = Choices(
    'Bank',
    'Digital Wallet',
    'Cash',
)


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='accounts_user')
    account_name = models.CharField(max_length=255)
    account_type = models.CharField(max_length=100, choices=ACCOUNT_TYPE, default=ACCOUNT_TYPE.Bank)
    created_at = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.account_name

    class Meta:
        db_table = 'money_account'


class Money(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='moneys_user')
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='moneys_account')
    transaction_period = models.ForeignKey(TransactionPeriod, on_delete=models.CASCADE, related_name='moneys_transaction_period')
    amount = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.amount)

    class Meta:
        db_table = 'money_money'

    @staticmethod
    def get_total_amount_in_account(user):
        total_amount = Money.objects.filter(transaction_period__is_active=True, user=user).aggregate(total=Sum('amount'))
        return total_amount

money/forms.py
from django import forms
from money.models import Account, Money


class AccountCreateForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = {
            'account_name',
            'account_type',
        }

        widgets = {
            'account_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account Name'}),
            'account_type' : forms.Select(attrs={'class': 'form-control'}),
        }


class AccountEditForm(forms.ModelForm):

    class Meta:
        model = Account
        fields = {
            'account_name',
            'account_type',
        }

        widgets = {
            'account_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Account Name'}),
            'account_type' : forms.Select(attrs={'class': 'form-control'}),
        }


class AddMoneyForm(forms.ModelForm):

    account = forms.ModelChoiceField(
        label='Account',
        queryset=Account.objects.filter(is_deleted=False),
        empty_label='Select Account Type',
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Money
        fields = {
            'account',
            'amount',
        }

        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Amount'}),
        }

money/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from income_expense.models import Income
from money.forms import AccountCreateForm, AccountEditForm, AddMoneyForm
from money.models import Account, Money
from transaction_period.models import TransactionPeriod
from users.decorators import login_required


# To list all the accounts and edit or delete the account
@login_required
def manage_account(request):
    context = {}

    accounts = Account.objects.filter(is_deleted=False, user=request.user,
                                      moneys_account__transaction_period__is_active=True)
    transaction_period = TransactionPeriod.get_active_transaction_period(user=request.user)

    context['transaction_period'] = transaction_period
    context['accounts'] = accounts
    return render(request, 'money/manage_accounts.html', context)


# Lists account on homepage with the amount in the respective account
@login_required
def account_list(request):
    context = {}
    accounts = Account.objects.filter(is_deleted=False, user=request.user,
                                      moneys_account__transaction_period__is_active=True)

    total_amount = Money.get_total_amount_in_account(user=request.user)

    transaction_period = TransactionPeriod.get_active_transaction_period(user=request.user)

    context['total_amount'] = total_amount
    context['accounts'] = accounts
    context['transaction_period'] = transaction_period
    return render(request, 'money/list_account.html', context)


@login_required
def add_account(request):
    context = {}

    form = AccountCreateForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            account = form.save(commit=False)
            account.user = request.user
            account.save()

            messages.info(request, 'New Account Created')
            return redirect('money:add_account')

    context['form'] = form
    return render(request, 'money/add_account.html', context)


@login_required
def edit_account(request, pk):
    context = {}

    try:
        account = Account.objects.get(pk=pk)
    except Account.DoesNotExist:
        messages.error(request, 'Account Does not Exist')
        return redirect('money:add_account')

    form = AccountEditForm(request.POST or None, instance=account)

    if request.method == 'POST':
        if form.is_valid():
            account = form.save()
            account.save()

            messages.info(request, 'Account Updated')
            return redirect('money:add_account')

    context['form'] = form
    return render(request, 'money/edit_account.html', context)


# delete account
@login_required
def add_money(request):
    context = {}

    try:
        active_transaction_period = TransactionPeriod.objects.get(is_active=True, user=request.user, is_closed=False)
    except TransactionPeriod.DoesNotExist:
        messages.error(request, 'Active and opne Transaction Period Not found, please open activate or create at least one')
        return redirect('transaction_period:transaction_period_list')

    form = AddMoneyForm(request.POST or None)

    # Filters the account foreign key based on user logged in
    form.fields["account"].queryset = Account.objects.filter(is_deleted=False, user=request.user)

    if request.method == 'POST':
        if form.is_valid():
            money = form.save(commit=False)

            # Check if money in selected account exist and if exist return back to home throwing error

            check_money_in_account = Money.objects.filter(user=request.user, account=money.account)
            if check_money_in_account.exists():
                messages.error(request, 'Money can be added only once in each Account,please use add income to add money')
                return redirect('money:list_account')

            money.user = request.user
            money.transaction_period = active_transaction_period

            # add money to income model too

            income = Income()
            income.account = money.account
            income.income_amount = money.amount
            income.user = request.user
            income.transaction_period = active_transaction_period
            income.description = 'Balance added directly in {}'.format(money.account.account_name)
            income.save()

            money.save()

            messages.info(request, 'Money Added')
            return redirect('money:add_account')

    context['form'] = form
    return render(request, 'money/add_money.html', context)

money/templates/money/add_account.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Add New Account{% endblock %}

{% block body %}


    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>New Account | <small>Add New Account</small></h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.account_name.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.account_name.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.account_name }}
                                    {% if form.account_name.errors %}
                                        <div class="form-text text-danger">{{ form.account_name.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.account_type.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.account_type.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.account_type }}
                                    {% if form.account_type.errors %}
                                        <div class="form-text text-danger">{{ form.account_type.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

money/templates/money/add_money.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Add Money {% endblock %}

{% block body %}


    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>Money | <small>Add Money</small></h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.account.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.account.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.account }}
                                    {% if form.account.errors %}
                                        <div class="form-text text-danger">{{ form.account.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.amount.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.amount.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.amount }}
                                    {% if form.amount.errors %}
                                        <div class="form-text text-danger">{{ form.amount.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

money/templates/money/edit_account.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Edit Account{% endblock %}

{% block body %}

    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>Edit Account</h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.account_name.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.account_name.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.account_name }}
                                    {% if form.account_name.errors %}
                                        <div class="form-text text-danger">{{ form.account_name.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.account_type.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.account_type.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.account_type }}
                                    {% if form.account_type.errors %}
                                        <div class="form-text text-danger">{{ form.account_type.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

money/templates/money/list_account.html
{% extends 'user_dashboard_base.html' %}
{% load money_tags %}

{% block title %}Accounts List {% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row mt-3">
        {% if transaction_period.is_closed %}
            <div class="col-12">
                <h3 class="text-center">Accounts List</h3>
            </div>
        {% else %}
            <div class="col-8">
                <h3 class="text-center">Accounts List</h3>
            </div>

            <div class="col-4">
                <div class="float-right">
                    <a href="{% url 'money:add_account' %}" class="btn btn-sm btn-primary">New Account</a>
                    <a href="{% url 'money:add_money' %}" class="btn btn-sm btn-success">Add Money</a>
                </div>
            </div>
        {% endif %}

    </div>

    {% if messages %}
        <div class="row">
            <div class="offset-2 col-md-6">
                {% for message in messages %}
                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                        <button type="button" class="close" data-dismiss="alert">X</button>
                        <p>{{ message }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}

        <div class="row">
            {% for account in accounts %}
                <div class="col-md-4">
                    <a href="#" class="text-decoration-none">
                        <div class="card card-shadow card-bg1 mt-3 ml-3 mb-3 text-center text-white">
                            <div class="card-body">
                                <h3>{{ account.account_name }}</h3>
                                <h5 class="lead">{{ account.account_type }}</h5>
                                {% if transaction_period.is_closed %}
                                    <p class="text-white">RS. {% get_money_close_transaction_account account.id %}</p>
                                {% else %}
                                    <p class="text-white">RS. {% get_money_active_transaction_account account.id %}</p>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        <hr>
        <div class="row">
            <div class="col-md-4 offset-1 text-left">
                <h3>Total Balance</h3>
                {% if transaction_period %}
                    <p>Transaction Period: <strong>{{ transaction_period.name }}
                        {% if transaction_period.is_closed %} (Closed){% endif %}</strong>
                    </p>
                {% endif %}
            </div>
            <div class="col-md-6 text-right">
                {% if total_amount.total > 0 %}
                    <h3>RS. {{ total_amount.total }}</h3>
                {% else %}
                    <h3>RS. 0</h3>
                {% endif %}
            </div>
        </div>
</div>

{% endblock %}

money/templates/money/manage_accounts.html
{% extends 'user_dashboard_base.html' %}
{% load money_tags %}

{% block title %} Manage Accounts {% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h4 class="text-center p-3">Manage Accounts</h4>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                        <tr class="text-center">
                            <th>S.N</th>
                            <th>Created Date</th>
                            <th>Account Name</th>
                            <th>Account Type</th>
                            <th>Amount (RS.)</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for account in accounts %}
                            <tr class="text-center">
                                <td>{{ forloop.counter }}</td>
                                <td>{{ account.created_at }}</td>
                                <td>{{ account.account_name }}</td>
                                <td>{{ account.account_type }}</td>
                                <td>
                                    {% if transaction_period.is_closed %}
                                        <p>RS. {% get_money_close_transaction_account account.id %}</p>
                                    {% else %}
                                        <p>RS. {% get_money_active_transaction_account account.id %}</p>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'money:edit_account' account.pk %}">
                                        <button type="button" class="btn btn-info btn-sm shadow">
                                            Edit<i class="fas fa-edit p-1"></i>
                                        </button>
                                    </a>
                                    <a href="#">
                                        <button type="button" class="btn btn-danger btn-sm shadow">
                                            Delete<i class="fas fa-trash-alt p-1"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}