income_expense/urls.py
from django.urls import path
from income_expense import views

app_name = 'income_expense'

urlpatterns = [
    path('add-income/', views.income_add, name='income_add'),
    path('list-income/', views.income_list, name='income_list'),

    path('add-expense/', views.expense_add, name='expense_add'),
    path('list-expense/', views.expense_list, name='expense_list'),
]

money/urls.py
from django.urls import path
from money import views


app_name = 'money'

urlpatterns = [
    path('manage-accounts/', views.manage_account, name='mange_accounts'),
    path('list-account/', views.account_list, name='list_account'),
    path('add-account/', views.add_account, name='add_account'),
    path('edit-account/<int:pk>/', views.edit_account, name='edit_account'),

    path('add-money/', views.add_money, name='add_money'),
]

moneytracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
    path('user/', include('users.urls')),
    path('dashboard/money/', include('money.urls')),
    path('dashboard/income-expense/', include('income_expense.urls')),
    path('dashboard/transaction/', include('transaction_period.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('dashboard/report/bar-graph/', views.bar_report_home, name='bar_report_home'),
    path('dashboard/report/income-expense/json/', views.income_expense_bar_chart, name='bar_report_chart')
]

transaction_period/urls.py
from django.urls import path
from transaction_period import views


app_name = 'transaction_period'

urlpatterns = [
    path('settings/', views.transaction_settings_home, name='transaction_settings_home'),
    path('period/list/', views.transaction_period_list, name='transaction_period_list'),
    path('period/add/', views.transaction_period_create, name='transaction_period_create'),
    path('period/change/', views.transaction_period_change, name='transaction_period_change'),
    path('period/edit/<int:pk>/', views.transaction_period_edit, name='transaction_period_edit'),
    path('close/transaction-period/', views.close_transaction_period, name='transaction_period_close'),
]

users/urls.py
from django.urls import path
from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
]

templates/includes/sidebar.html
<div>
    <!-- Sidebar -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <h3><a href={% url 'money:list_account' %}>Money Tracker</a></h3>
        </div>

        <ul class="list-unstyled components">
            <li class="active">
                <a href="#accounts" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Account</a>
                <ul class="collapse list-unstyled" id="accounts">
                    <li>
                        <a href="{% url 'money:list_account' %}">Accounts List</a>
                    </li>
                    <li>
                        <a href="{% url 'money:add_account' %}">New Account</a>
                    </li>
                    <li>
                        <a href="{% url 'money:mange_accounts' %}">Manage Accounts</a>
                    </li>
                    <li>
                        <a href="{% url 'money:add_money' %}">Add Money</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#incomes" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Income</a>
                <ul class="collapse list-unstyled" id="incomes">
                    <li>
                        <a href="{% url 'income_expense:income_add' %}">Add Income</a>
                    </li>
                    <li>
                        <a href="{% url 'income_expense:income_list' %}">Income Report</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="#expenses" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Expense</a>
                <ul class="collapse list-unstyled" id="expenses">
                    <li>
                        <a href="{% url 'income_expense:expense_add' %}">Add Expense</a>
                    </li>
                    <li>
                        <a href="{% url 'income_expense:expense_list' %}">Expense Report</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="{% url 'transaction_period:transaction_settings_home' %}">Transaction Settings</a>
            </li>
            <li>
                <a href="{% url 'pages:bar_report_home' %}">Income Expense Bar Chart</a>
            </li>
            <li>
                <a href="{% url 'users:user_logout' %}">Logout</a>
            </li>
        </ul>
    </nav>

</div>