money/urls.py
from django.urls import path
from money import views


app_name = 'money'

urlpatterns = [
    path('manage-accounts/', views.manage_account, name='mange_accounts'),
    path('list-account/', views.account_list, name='list_account'),
    path('add-account/', views.add_account, name='add_account'),
    path('edit-account/<int:pk>/', views.edit_account, name='edit_account'),

    path('add-money/', views.add_money, name='add_money'),
]

moneytracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
    path('user/', include('users.urls')),
    path('dashboard/money/', include('money.urls')),
    path('dashboard/income-expense/', include('income_expense.urls')),
    path('dashboard/transaction/', include('transaction_period.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transaction_period/urls.py
from django.urls import path
from transaction_period import views


app_name = 'transaction_period'

urlpatterns = [
    path('settings/', views.transaction_settings_home, name='transaction_settings_home'),
    path('period/list/', views.transaction_period_list, name='transaction_period_list'),
    path('period/add/', views.transaction_period_create, name='transaction_period_create'),
    path('period/change/', views.transaction_period_change, name='transaction_period_change'),
    path('period/edit/<int:pk>/', views.transaction_period_edit, name='transaction_period_edit'),
    path('close/transaction-period/', views.close_transaction_period, name='transaction_period_close'),
]

transaction_period/models.py
from django.db import models

from users.models import User


class TransactionPeriod(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    name = models.CharField(max_length=255)
    start_date = models.DateField()
    end_date = models.DateField()
    is_closed = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)

    class Meta:
        db_table = 'transaction_period'

    def __str__(self):
        return self.name

    @staticmethod
    def get_active_transaction_period(user):
        try:
            transaction_period = TransactionPeriod.objects.get(is_active=True, user=user)
        except TransactionPeriod.DoesNotExist:
            transaction_period = None
        return transaction_period

transaction_period/forms.py
from django import forms

from transaction_period.models import TransactionPeriod


class TransactionPeriodCreateForm(forms.ModelForm):

    class Meta:
        model = TransactionPeriod
        fields = {
            'name',
            'start_date',
            'end_date',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Transaction Period Name'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def clean(self):
        cleaned_date = super(TransactionPeriodCreateForm, self).clean()

        start_date = cleaned_date.get('start_date')
        end_date = cleaned_date.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                self.add_error('start_date', 'Start Date must be smaller than end date')
        return cleaned_date


class TransactionPeriodEditForm(forms.ModelForm):

    class Meta:
        model = TransactionPeriod
        fields = {
            'name',
            'start_date',
            'end_date',
        }

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Transaction Period Name'}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date'}),
        }

    def clean(self):
        cleaned_date = super(TransactionPeriodEditForm, self).clean()

        start_date = cleaned_date.get('start_date')
        end_date = cleaned_date.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                self.add_error('start_date', 'Start Date must be smaller than end date')
        return cleaned_date


class TransactionPeriodChangeForm(forms.Form):
    transaction_period = forms.ModelChoiceField(
        label='Transaction Periods',
        queryset=TransactionPeriod.objects.filter(is_active=False),
        empty_label='Select Transaction Period',
        widget=forms.Select(attrs={'class': 'form-control'})
    )


class CloseTransactionPeriodForm(forms.ModelForm):

    name = forms.ModelChoiceField(
        label='Transaction Periods',
        queryset=TransactionPeriod.objects.filter(is_active=False),
        empty_label='Select New Transaction Period',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = TransactionPeriod
        fields = {
            'name'
        }

transaction_period/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from money.models import Account, Money
from transaction_period.forms import TransactionPeriodCreateForm, TransactionPeriodChangeForm, \
    CloseTransactionPeriodForm
from transaction_period.models import TransactionPeriod
from users.decorators import login_required


@login_required
def transaction_settings_home(request):
    context = {}
    return render(request, 'transaction_period/transaction_settings_home.html', context)


@login_required
def transaction_period_list(request):
    context = {}

    transaction_periods = TransactionPeriod.objects.filter(is_active=True, is_closed=False, user=request.user)
    context['transaction_periods'] = transaction_periods
    return render(request, 'transaction_period/transaction_period_list.htm', context)


@login_required
def transaction_period_create(request):
    context = {}

    form = TransactionPeriodCreateForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            transaction_period = form.save(commit=False)
            transaction_period.user = request.user
            transaction_period.save()
            messages.info(request, 'New Transaction Period Added')
            return redirect('transaction_period:transaction_period_list')

    context['form'] = form
    return render(request, 'transaction_period/transaction_period_add.htm', context)


@login_required
def transaction_period_edit(request, pk):
    context = {}

    try:
        transaction_period = TransactionPeriod.objects.get(pk=pk, user=request.user)
    except TransactionPeriod.DoesNotExist:
        messages.error(request, 'Transaction Period Does Not Exist!')
        return redirect('transaction_period:transaction_period_list')

    form = TransactionPeriodCreateForm(request.POST or None, instance=transaction_period)

    if request.method == 'POST':
        if form.is_valid():
            transaction_period = form.save(commit=False)
            transaction_period.save()
            messages.info(request, 'Transaction Period Updated')
            return redirect('transaction_period:transaction_period_list')

    context['form'] = form
    return render(request, 'transaction_period/transaction_period_edit.htm', context)


@login_required
def transaction_period_change(request):
    context = {}

    form = TransactionPeriodChangeForm(request.POST or None)
    form.fields['transaction_period'].queryset = TransactionPeriod.objects.filter(is_active=False, user=request.user)

    if request.method == 'POST':
        if form.is_valid():
            for tp in TransactionPeriod.objects.filter(is_active=True, user=request.user):
                tp.is_active = False
                tp.save()

            transaction_period = form.cleaned_data['transaction_period']
            transaction_period.is_active = True
            transaction_period.save()

            messages.info(request, "Transaction changed successfully!")
            return redirect('transaction_period:transaction_period_list')

    context['form'] = form
    return render(request, 'transaction_period/transaction_period_change.html', context)


@login_required
def close_transaction_period(request):
    context = {}

    # active_transaction_period = TransactionPeriod.get_active_transaction_period(user=request.user)
    # if active_transaction_period.is_closed:
    #     messages.error(request, 'Currently Active Transaction Period is already Closed')
    #     return redirect('transaction_period:transaction_settings_home')

    money = Money.objects.filter(transaction_period__is_active=True, transaction_period__is_closed=False,
                                 user=request.user)

    form = CloseTransactionPeriodForm(request.POST or None)
    form.fields['name'].queryset = TransactionPeriod.objects.filter(is_active=False, is_closed=False, user=request.user)

    if request.method == 'POST':
        if form.is_valid():

            # closing active transaction period and adding opening balance in new transaction period

            for m in money:
                new_m = Money()
                new_m.amount = m.amount
                new_m.account = m.account
                new_m.user = request.user
                new_m.transaction_period = form.cleaned_data['name']
                new_m.save()

            for atp in TransactionPeriod.objects.filter(is_active=True, is_closed=False, user=request.user):
                atp.is_active = False
                atp.is_closed = True
                atp.save()

            tp = form.cleaned_data['name']
            tp.is_active = True
            tp.save()

            return redirect('transaction_period:transaction_period_close')
    context['form'] = form
    context['money'] = money
    return render(request, 'transaction_period/transaction_period_close.html', context)

transaction_period/templates/transaction_period/transaction_period_add.htm
{% extends 'user_dashboard_base.html' %}

{% block title %}Add Transaction Period{% endblock %}

{% block body %}


    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>Transaction Period | <small>Add New Transaction Period</small></h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.name.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.name }}
                                    {% if form.name.errors %}
                                        <div class="form-text text-danger">{{ form.name.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.start_date.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.start_date.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.start_date }}
                                    {% if form.start_date.errors %}
                                        <div class="form-text text-white">{{ form.start_date.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.end_date.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.end_date.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.end_date }}
                                    {% if form.end_date.errors %}
                                        <div class="form-text text-danger">{{ form.end_date.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

transaction_period/templates/transaction_period/transaction_period_change.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Change Transaction Period{% endblock %}

{% block body %}


    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>Transaction Period | <small>Change Transaction Period</small></h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.transaction_period.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.transaction_period.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.transaction_period }}
                                    {% if form.transaction_period.errors %}
                                        <div class="form-text text-danger">{{ form.transaction_period.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

transaction_period/templates/transaction_period/transaction_period_close.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Close Transaction Period{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-center p-3">Close Transaction Period</h3>
            </div>
        </div>
        <hr>

        {% if messages %}
            <div class="row">
                <div class="offset-2 col-md-6">
                    {% for message in messages %}
                        <div class="alert alert-dismissible alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert">X</button>
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row">
            <div class="col-md-12">
                <form method="post" class="pt-3">
                    {% csrf_token %}
                    <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                        <label class="col-md-3 offset-1">{{ form.name.label }} <span class="text-danger required-field">*</span></label>
                            <div class="col-md-9 offset-1">
                                {{ form.name }}
                                {% if form.name.errors %}
                                    <div class="form-text text-danger">{{ form.name.errors }}</div>
                                {% endif %}
                            </div>
                    </div>
                    <div class="form-group">
                        <div class="offset-1 col-md-3">
                            <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Close and Transfer</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-md-10 offset-1">
                <h3><u>Things To Note</u></h3>
                <uL>
                    <li>The above form will close the currently active transaction period</li>
                    <li>In the select field above, select the transaction period which you want to activate or use next.</li>
                    <li>Final Balance from current active transaction period will be transferred to above selected transaction period as opening balance.</li>
                    <li>After the transfer is complete, selected transaction period will be activated.</li>
                </uL>
            </div>
        </div>
    </div>
{% endblock %}

transaction_period/templates/transaction_period/transaction_period_edit.htm
{% extends 'user_dashboard_base.html' %}

{% block title %}Edit Transaction Period{% endblock %}

{% block body %}


    <div class="container-fluid">

        <div class="row mt-5">
            <div class="col-md-8 offset-2">
                <div class="card card-bg card-shadow text-white mb-5">
                    <div class="row mt-5 mb-3">
                        <div class="col-md-9 offset-1">
                            <h4>Transaction Period | <small>Edit Transaction Period</small></h4>
                            <hr>
                        </div>
                    </div>

                    {% if messages %}
                        <div class="row">
                            <div class="offset-md-2 col-md-6">
                                {% for message in messages %}
                                    <div class="alert alert-dismissible alert-{{ message.tags }}">
                                        <button type="button" class="close" data-dismiss="alert">X</button>
                                        <p>{{ message }}</p>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}


                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group {% if form.name.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.name.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.name }}
                                    {% if form.name.errors %}
                                        <div class="form-text text-danger">{{ form.name.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.start_date.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.start_date.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.start_date }}
                                    {% if form.start_date.errors %}
                                        <div class="form-text text-white">{{ form.start_date.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group {% if form.end_date.errors %}has-error{% endif %}">
                            <label class="col-md-3 offset-1">{{ form.end_date.label }} <span class="text-danger required-field">*</span></label>
                                <div class="col-md-9 offset-1">
                                    {{ form.end_date }}
                                    {% if form.end_date.errors %}
                                        <div class="form-text text-danger">{{ form.end_date.errors }}</div>
                                    {% endif %}
                                </div>
                        </div>

                        <div class="form-group">
                            <div class="offset-md-1 col-md-3">
                                <button type="submit" name="submit" class="mt-4 btn btn-primary btn-block border-0 button-bg">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

{% endblock %}

transaction_period/templates/transaction_period/transaction_period_list.htm
{% extends 'user_dashboard_base.html' %}

{% block title %}Transaction Period List{% endblock %}

{% block body %}
    <div class="container-fluid">

        {% if messages %}
            <div class="row">
                <div class="offset-md-2 col-md-6">
                    {% for message in messages %}
                        <div class="alert alert-dismissible alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert">X</button>
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row mt-3 p-3">
            <div class="col-md-8 text-center">
                <h3>Active Transaction Period</h3>
            </div>
            <div class="col-md-4">
                <div class="float-right">
                    <a href="{% url 'transaction_period:transaction_period_create' %}" class="btn btn-sm btn-primary">Create New</a>
                    <a href="{% url 'transaction_period:transaction_period_change' %}" class="btn btn-sm btn-primary">Change</a>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <table class="table table-hover table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for tp in transaction_periods %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ tp.name }} (Active)</td>
                                <td>{{ tp.start_date }}</td>
                                <td>{{ tp.end_date }}</td>
                                <td>
                                    <a href="{% url 'transaction_period:transaction_period_edit' tp.pk %}">
                                        <button type="button" class="btn btn-info btn-sm shadow">
                                            Edit<i class="fas fa-edit p-1"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

transaction_period/templates/transaction_period/transaction_settings_home.html
{% extends 'user_dashboard_base.html' %}

{% block title %}Transaction Settings{% endblock %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-center p-3">Transaction Settings</h3>
            </div>
        </div>

        {% if messages %}
            <div class="row">
                <div class="offset-2 col-md-6">
                    {% for message in messages %}
                        <div class="alert alert-dismissible alert-{{ message.tags }}">
                            <button type="button" class="close" data-dismiss="alert">X</button>
                            <p>{{ message }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row mt-3">
            <div class="col-md-3">
                <a href="{% url 'transaction_period:transaction_period_list' %}">
                    <div class="card card-shadow card-bg1 text-white">
                        <div class="card-body">
                            <div class="text-center">
                                <i class="far fa-calendar-alt fa-2x"></i>
                                <h4 class="p-1">Transaction Periods List</h4>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="{% url 'transaction_period:transaction_period_create' %}">
                    <div class="card card-shadow card-bg1 text-white">
                        <div class="card-body">
                            <div class="text-center">
                                <i class="fas fa-plus fa-2x"></i>
                                <h4 class="p-1">New Transaction Period</h4>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="{% url 'transaction_period:transaction_period_change' %}">
                    <div class="card card-shadow card-bg1 text-white">
                        <div class="card-body">
                            <div class="text-center">
                                <i class="fas fa-exchange-alt fa-2x"></i>
                                <h4 class="p-1">Change Transaction Period</h4>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-3">
                <a href="{% url 'transaction_period:transaction_period_close' %}">
                    <div class="card card-shadow card-bg1 text-white">
                        <div class="card-body">
                            <div class="text-center">
                                <i class="fas fa-file-invoice-dollar fa-2x"></i>
                                <h4 class="p-1">Close Transaction Period</h4>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}