money/urls.py
from django.urls import path
from money import views


app_name = 'money'

urlpatterns = [
    path('manage-accounts/', views.manage_account, name='mange_accounts'),
    path('list-account/', views.account_list, name='list_account'),
    path('add-account/', views.add_account, name='add_account'),
    path('edit-account/<int:pk>/', views.edit_account, name='edit_account'),

    path('add-money/', views.add_money, name='add_money'),
]

moneytracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('pages.urls')),
    path('user/', include('users.urls')),
    path('dashboard/money/', include('money.urls')),
    path('dashboard/income-expense/', include('income_expense.urls')),
    path('dashboard/transaction/', include('transaction_period.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from model_utils import Choices

from .validators import UsernameValidator

USER_ROLES = Choices(
    'superadmin',
    'enduser',
)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **kwargs):
        if not email:
            raise ValueError("Please enter a valid Email Address")

        if not kwargs.get('username'):
            raise ValueError('Please enter a valid username')

        user = self.model(
            username=kwargs.get('username').strip(),
            email=self.normalize_email(email),
            first_name=kwargs.get('first_name'),
            middle_name=kwargs.get('middle_name'),
            last_name=kwargs.get('last_name'),
        )

        user.set_password(password)
        user.save()

        return user

    def create_superuser(self, email, password, **kwargs):
        user = self.create_user(email, password, **kwargs)

        user.role = 'superadmin'
        user.is_confirmed = True
        user.save()

        return user


class User(AbstractBaseUser):
    username = models.CharField(
        max_length=250,
        unique=True,
        validators=[UsernameValidator()],
        error_messages={
            'unique': 'username already taken',
        },
    )

    email = models.EmailField(
        unique=True,
        error_messages={
            'unique': 'email already exist',
        },
    )
    first_name = models.CharField(max_length=255)
    middle_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255)
    is_confirmed = models.BooleanField(default=False)
    role = models.CharField(max_length=100, choices=USER_ROLES, default=USER_ROLES.superadmin)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email

    class Meta:
        db_table = 'user_user'

    def get_full_name(self):
        full_name = self.first_name

        if self.middle_name:
            full_name = full_name + ' ' + self.middle_name

        if self.last_name:
            full_name = full_name + ' ' + self.last_name

        return full_name

    def get_short_name(self):
        return self.first_name

    def is_superadmin(self):
        return self.role == USER_ROLES.superadmin

    def is_enduser(self):
        return self.role == USER_ROLES.enduser

users/forms.py
from django import forms
from users.models import User


class UserLoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Username or Email'}),
    )

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

    def clean_username(self):
        username = self.cleaned_data.get('username')

        try:
            user = User.objects.get(email=username)
        except User.DoesNotExist:
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                user = None

        if user:
            return user.email
        return None


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}),
    )

    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm Password'})
    )

    def clean(self):
        cleaned_data = super(UserRegisterForm, self).clean()

        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')

        # check for min length
        min_length = 8
        if len(password) < min_length:
            msg = 'Password must be at least %s characters long.' % (str(min_length))
            self.add_error('password', msg)

        # check for digit
        if sum(c.isdigit() for c in password) < 1:
            msg = 'Password must contain at least 1 number.'
            self.add_error('password', msg)

        # check for uppercase letter
        if not any(c.isupper() for c in password):
            msg = 'Password must contain at least 1 uppercase letter.'
            self.add_error('password', msg)

        # check for lowercase letter
        if not any(c.islower() for c in password):
            msg = 'Password must contain at least 1 lowercase letter.'
            self.add_error('password', msg)

        if password and confirm_password:
            if password != confirm_password:
                self.add_error('confirm_password', "Passwords didn't match")

        return cleaned_data

    class Meta:
        model = User
        fields = {
            'username',
            'email',
            'first_name',
            'last_name',
            'password',
            'confirm_password',
        }

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Last Name'}),
        }

users/views.py
from django.contrib import messages
from django.contrib.auth import logout, authenticate, login
from django.shortcuts import render, redirect

from users.decorators import unauthenticated_user, login_required
from users.forms import UserLoginForm, UserRegisterForm
from users.models import USER_ROLES


@unauthenticated_user
def user_login(request):
    next = request.GET.get('next', None)

    context = {}

    form = UserLoginForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is None:
                messages.error(request, 'Invalid Login Details')
                return redirect('users:login')
            else:
                login(request, user)
                if next:
                    return redirect(next)
                return redirect('money:list_account')

    context['form'] = form
    return render(request, 'users/login.html', context)


@login_required
def user_logout(request):
    logout(request)
    messages.info(request, "Logged out Successfully!")
    return redirect('users:login')


@unauthenticated_user
def user_register(request):
    context = {}

    form = UserRegisterForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            user = form.save(commit=False)
            user.username = form.cleaned_data.get('username')
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            raw_password = form.cleaned_data.get('password')
            user.set_password(raw_password)
            user.role = USER_ROLES.enduser
            user.save()
            messages.info(request, 'User Created, please login')
            return redirect('users:login')

    context['form'] = form
    return render(request, 'users/user_register.html', context)

users/templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body %}
    <div class="container-fluid h-100">
        <div class="row h-100">
            <div class="col-md-4 offset-4 my-auto">

                {% if messages %}
                    <div class="row">
                        <div class="offset-md-3 col-md-6">
                            {% for message in messages %}
                                <div class="alert alert-dismissible alert-{{ message.tags }}">
                                    <button type="button" class="close" data-dismiss="alert">X</button>
                                    <p>{{ message }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                <div class="card card-shadow">
                    <div class="body">
                        <div class="card-title mt-5 mb-5">
                            <h3 class="text-center">Account Login</h3>
                        </div>
                        <div class="row">
                            <div class="col-md-10 offset-1 mb-5">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                                        {{ form.username }}
                                        {% if form.username.errors %}
                                            <div class="form-text text-danger">{{ form.username.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group">
                                        {{ form.password }}
                                        {% if form.password.errors %}
                                            <div class="form-text text-danger">{{ form.password.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="row">
                                        <div class="col-md-5 offset-3">
                                           <div class="form-group">
                                                <button class="btn btn-outline-primary btn-block" type="submit" name="submit">
                                                    Login
                                                </button>
                                              </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 offset-3">
                               <div class="form-group">
                                   <a href="{% url 'users:user_register' %}" class="text-decoration-none">
                                       <button class="btn btn-outline-primary btn-block" type="submit" name="submit">
                                            Register
                                        </button>
                                   </a>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_register.html
{% extends 'base.html' %}

{% block title %} User Registration {% endblock %}

{% block body %}
    <div class="container-fluid h-100">
        <div class="row h-100">
            <div class="col-md-4 offset-4 my-auto">

                {% if messages %}
                    <div class="row">
                        <div class="offset-md-3 col-md-6">
                            {% for message in messages %}
                                <div class="alert alert-dismissible alert-{{ message.tags }}">
                                    <button type="button" class="close" data-dismiss="alert">X</button>
                                    <p>{{ message }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}

                <div class="card card-shadow">
                    <div class="body">
                        <div class="card-title mt-5 mb-5">
                            <h3 class="text-center">Create An Account</h3>
                        </div>
                        <div class="row">
                            <div class="col-md-10 offset-1 mb-3">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-group {% if form.first_name.errors %}has-error{% endif %}">
                                        {{ form.first_name }}
                                        {% if form.first_name.errors %}
                                            <div class="form-text text-danger">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group {% if form.last_name.errors %}has-error{% endif %}">
                                        {{ form.last_name }}
                                        {% if form.last_name.errors %}
                                            <div class="form-text text-danger">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group {% if form.username.errors %}has-error{% endif %}">
                                        {{ form.username }}
                                        {% if form.username.errors %}
                                            <div class="form-text text-danger">{{ form.username.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group {% if form.email.errors %}has-error{% endif %}">
                                        {{ form.email }}
                                        {% if form.email.errors %}
                                            <div class="form-text text-danger">{{ form.email.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group">
                                        {{ form.password }}
                                        {% if form.password.errors %}
                                            <div class="form-text text-danger">{{ form.password.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="form-group">
                                        {{ form.confirm_password }}
                                        {% if form.confirm_password.errors %}
                                            <div class="form-text text-danger">{{ form.confirm_password.errors }}</div>
                                        {% endif %}
                                    </div>

                                    <div class="row">
                                        <div class="col-md-5 offset-3">
                                           <div class="form-group pt-3">
                                                <button class="btn btn-outline-primary btn-block" type="submit" name="submit">
                                                    Register
                                                </button>
                                           </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5 offset-3">
                               <div class="form-group">
                                   <p>Already have an account?</p>
                                   <a href="{% url 'users:login' %}" class="text-decoration-none">
                                       <button class="btn btn-outline-primary btn-block" type="submit" name="submit">
                                            Login
                                        </button>
                                   </a>
                               </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-8 offset-1">
                                <small>All Fields are Required</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}